### ISSUE TITLE
内部用と外部（ActivityPub）用で違うアセットドメインが使えるようにする

### ISSUE THREAD

**Issue by u1-liquid** [MisskeyIO/misskey#569]

**Comment by tomakun** [comment]
こちらはとても重要だと思っています。

先日Misskey.ioにてアセットドメインが変わった結果、リモートサーバ（Misskey, Mastodonなど）側でドメイン変更前の画像が正しく読み込まれなくなり（表示されない）、かなり大きい損害になってしまっています。

media.misskeyusercontent.com から media.misskeyusercontent.jp

上記はリダイレクトなしで実行されてしまっているのでしょうか？

  現状、リモートサーバ側で解決をするために、DB上のURLをReplaceし始めている管理者もいるようですが、この問題はそちらで解決する予定はありますでしょうか？
  
  よろしくお願い致します。

**Comment by u1-liquid** [comment]
This issue is not related to the mentioned outage or domain change.

**Comment by tomakun** [comment]
@u1-liquid Thanks for your comment! Should I open a separate issue for this? Do you have any information about the resolution of the mentioned outage?
